### ISSUE TITLE
[bug] .test.ts file name pattern is not supported

### ISSUE THREAD

**Issue by wizzard0** [johtela/litscript#13]
I believe this is a separate issue from #12, and it's a bug, because .test.ts files don't contain JSX markup and should be picked up fine with regular TypeScript parser.

Expected Behaviour:
- `.test.ts` files are compiled as regular typescript

Observed Behaviour:
- Translator not registered for file `index.test.ts`

Steps to reproduce:
- See #12 , then add `index.test.ts` file

**Comment by johtela** [comment]
Duplicate of #12
