### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve 'ts-loader' 

### ISSUE THREAD

**Issue by rix0rrr** [johtela/litscript#19]
As far as I know I'm not doing anything weird. I just did:

```
$ npm install --save-dev litscript
```

Into an existing project, did some configging, and am then running `npx lits`. However, I'm getting the following error during the **bundling** phase:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'ts-loader' in '/my/project/dir'
```

(Skipping bundling is not an option, I need the js/css that webpack is supposed to be generating)

Plugging a debugger into webpack, I can see the fuller version of the error message is:

```
resolve 'ts-loader' in '/my/project/dir'
  Parsed request is a module
  using description file: /my/project/dir/package.json (relative path: .)
    resolve as module
      looking for modules in /my/project/dir/node_modules/litscript/node_modules
        single file module
          using description file: /my/project/dir/node_modules/litscript/package.json (relative path: ./node_modules/ts-loader)
            no extension
              /my/project/dir/node_modules/litscript/node_modules/ts-loader doesn't exist
            .js
              /my/project/dir/node_modules/litscript/node_modules/ts-loader.js doesn't exist
        /my/project/dir/node_modules/litscript/node_modules/ts-loader doesn't exist'
```

For whatever reason, webpack seems to be trying to load `ts-loader` only from

```
/my/project/dir/node_modules/litscript/node_modules/ts-loader
```

While `npm` hoisted it to:

```
/my/project/dir/node_modules/ts-loader
```

Why is this happening? What can I do about it?

**Comment by rix0rrr** [comment]
The issue seems to be a local install vs a global install!

It looks like `findNodeModulesDir()` is trying to be clever in a way that breaks a local install.

In my NPM  tree, it seems to be the case that some dependencies are hoisted, and some are not because of version conflicts (specifically, `typescript`). This leads to the following tree:

```
/my/project
  node_modules
    litscript
      node_modules
         typescript
    typescript
    webpack
    ts-loader
```

`findNodeModulesDir()` looks like this:

```ts
function findNodeModulesDir() {
    let res = path.resolve(__dirname, "..", nmdir);
    if (fs.existsSync(res)) // <--- (A)
        return res;
    res = path.resolve(__dirname, "../..");
    if (path.basename(res) == nmdir)
        return res;
    throw Error(`Could not find "${nmdir}" directory`);
}
```

It will *find* the `node_modules/litscript/node_modules` directory at `(A)`, and assume that directory will also contain the loader. 

That is not true however, the loader has been hoisted to the top level directory.

**Comment by johtela** [comment]
Thanks for investigating this yourself. It seems definitely a fixable problem. I'm on holiday right now but will give this some time next week when I'm back at home.

**Comment by johtela** [comment]
Changed the `findNodeModulesDir` to `nodeModulesDirs` function. It returns list of `node_modules` paths, which WebPack should scan one-by-one. So, hopefully now it can find `ts-loader` in either node directory.

Also updated npm dependencies to get rid of security warnings.
